DROP SCHEMA IF EXISTS `Web_DB`;
CREATE SCHEMA `Web_DB`;
USE `Web_DB`;
CREATE TABLE `PRODUCT`(
  `ID` BIGINT PRIMARY KEY NOT NULL,-- 4 số 
  `NAME` VARCHAR(100),
  `PRICE` INT,
  `IMG_URL` VARCHAR(250),
  `NUMBER` INT,
  `DECS` TEXT,
  `CATEGORY` VARCHAR(100),
  `TOP_PRODUCT` INT
);

CREATE TABLE `SUB_IMG_URL` (
    `ID` INT PRIMARY KEY,
    `PID` BIGINT NOT NULL,
    `IMG_URL` VARCHAR(250),
    FOREIGN KEY (`PID`) REFERENCES `PRODUCT`(`ID`)
);
CREATE TABLE `ACCOUNT` (
  `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `CMND` VARCHAR(10),
  `FNAME` VARCHAR(50),
  `PHONE` VARCHAR(10),
  `ADDRESS` TEXT,
  `USERNAME` VARCHAR(50),
  `PWD` VARCHAR(50),
  `RANK` INT
);
CREATE TABLE `ORDER_PRODUCT`(
  `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `PID` BIGINT NOT NULL,
  `QUANTITY` INT DEFAULT 0,
    FOREIGN KEY (`PID`) REFERENCES `PRODUCT`(`ID`)
);
CREATE TABLE `CART`(
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `UID` BIGINT NOT NULL,
    `OID` BIGINT NOT NULL,
    FOREIGN KEY (`OID`) REFERENCES `ORDER_PRODUCT`(`ID`) ,
    FOREIGN KEY (`UID`) REFERENCES `ACCOUNT`(`ID`) 
);
CREATE TABLE `COMMENT`(
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PID` BIGINT NOT NULL,
    `UID` BIGINT NOT NULL,
    `START` INT DEFAULT 5,
    `CONTENT` TEXT,
    `TIME` DATE,
    FOREIGN KEY (`UID`) REFERENCES `ACCOUNT`(`ID`) 
);
CREATE TABLE `NEW`(
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `KEY` VARCHAR(50),
    `TIME` DATE,
    `TITLE` VARCHAR(50),
    `CONTENT` TEXT,
    `CID` BIGINT NULL,
    `IMG_URL` VARCHAR(50),
    `SHORT_CONTENT` VARCHAR(300),
    FOREIGN KEY (`CID`) REFERENCES `COMMENT`(`ID`) 
);
CREATE TABLE `COMBO`(
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(50),
    `COST` INT DEFAULT 0
);
CREATE TABLE `PRODUCT_IN_COMBO`(
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `CBID` INT NOT NULL,
    `PID` BIGINT NOT NULL,
    FOREIGN KEY (`PID`) REFERENCES `PRODUCT`(`ID`),
    FOREIGN KEY (`CBID`) REFERENCES `COMBO`(`ID`)
);
CREATE TABLE `COST_TABLE`(
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `CBID` INT NOT NULL,
    `CYCLE` INT,
    FOREIGN KEY (`CBID`) REFERENCES `COMBO`(`ID`)
);
CREATE TABLE `MESSAGE`(
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `FNAME` INT NOT NULL,
    `EMAIL` VARCHAR(250),
    `PHONE` VARCHAR(10),
    `SUBJECT` VARCHAR(250),
    `CONTENT` TEXT
);
CREATE TABLE `ORDER_COMBO`(
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `UID` BIGINT,
    `CBID` INT NOT NULL,
    FOREIGN KEY (`CBID`) REFERENCES `COMBO`(`ID`),
    FOREIGN KEY (`UID`) REFERENCES `ACCOUNT`(`ID`)
);
CREATE TABLE `BAN_ACCOUNT`(
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `CMND` VARCHAR(10)
);